FROM quay.io/keycloak/keycloak:18.0.2

COPY  target/keycloak-justauth-12.0.1-jar-with-dependencies.jar /opt/keycloak/deployments/

CMD ["start-dev", "--hostname-strict=false", "--features=\"preview,scripts\""]