version: '3'

services:
  keycloak:
      build: 
        context: .
        dockerfile: Dockerfile.local
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        PORT: 8080
        DB_VENDOR: "h2"
      ports:
        - "8080:8080"
        - "9990:9990"
      volumes:
        - ~/.m2/repository:/root/.m2/repository
